### PR TITLE
Add a logo image.

### PR DESCRIPTION
**Pull request by DentonGentry**
This commit will add the PNG to github, which will let us get a URL for
it from https://www.jsdelivr.com/, which we can then add to
tailscale.nuspec as an <iconUrl>

### CODE REVIEW

**Comment by bradfitz** [comment]
Sure this is the wrong logo file? It looks .... very white:

https://raw.githubusercontent.com/tailscale/tailscale-chocolatey/d47e535200402c2d1eb6a68920ded1a12392a177/icon/Tailscale-Mark-White.png

Screen Shot 2021-06-08 at 7 51 36 AM

**Comment by DentonGentry** [comment]
Opacity strikes again, it looked ok with the background I happened to have at the time.

Filled in the background with a medium grey.

**Comment by rosszurowski** [comment]
Where is this image going? Just on [the Chocolatey repo](https://community.chocolatey.org/packages/tailscale)?

Here's an official Tailscale logo graphic you can use:

avatar

**Comment by rosszurowski** [comment]
In the future, you can find these graphics in our [internal brand guidelines](https://www.notion.so/tailscale/Brand-Guidelines-ef6387a4e53e4ba6b50bef432a549da1) and on our [public press kit](https://tailscale.com/static/dist/tailscale-press-kit.zip). If I can put these resources somewhere else that'd be easier to find, let me know!

**Comment by DentonGentry** [comment]
Yes, this is for the logo image in the Chocolatey repo. Updated to use the provided image.

**Comment by bradfitz** [comment]
Is this all that's needed, or does something need to happen in a metadata file too?

LGTM though

**Comment by DentonGentry** [comment]
We'll need to add it to tailscale.nuspec as an \<iconUrl\> (which was in the commit message but I hadn't escaped the \<\> so github didn't render it).

I could guess at what the https://www.jsdelivr.com/ URL would be to include it in this PR, but I'd rather commit it so I can test the URL and then add it to the tailscale.nuspec.

**Pull request merged**
